"""contratos e outbox (Fase 2, Tarefa 2.3)

Revision ID: 0001
Revises:

Tabelas do schema ``contratos`` (modelo em ``app/infrastructure/db/modelos.py``;
``alembic check`` confere). Alem do que o autogenerate gera:

- **Imutabilidade por trigger** (vale ate para o dono das tabelas; o ``REVOKE`` no
  papel da aplicacao, D14, e segunda camada no deploy):
  ``contract_events`` e ``contract_snapshots`` recusam ``UPDATE``, ``DELETE`` e
  ``TRUNCATE``; ``contract_submissions`` aceita um unico ``UPDATE`` (o que grava a
  resposta, sem mexer nos campos do envio) e recusa ``DELETE``/``TRUNCATE``.
- Linha unica do ``sap_heartbeat`` (``id = 1``).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_IMUTABILIDADE = (
    """
    CREATE FUNCTION contratos.proibir_alteracao() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION '%: registro imutavel (% proibido)', TG_TABLE_NAME, TG_OP
            USING ERRCODE = 'P0001';
    END
    $$
    """,
    """
    CREATE FUNCTION contratos.submissao_resposta_unica() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'contract_submissions: DELETE proibido';
        END IF;
        IF OLD.respondido THEN
            RAISE EXCEPTION 'contract_submissions: resposta ja gravada (imutavel)';
        END IF;
        IF NEW.respondido IS NOT TRUE THEN
            RAISE EXCEPTION 'contract_submissions: UPDATE so para gravar a resposta';
        END IF;
        IF (NEW.id, NEW.job_id, NEW.contract_id, NEW.snapshot_id, NEW.tentativa,
            NEW.request_sent_at, NEW.request_body, NEW.request_sha256, NEW.request_json)
           IS DISTINCT FROM
           (OLD.id, OLD.job_id, OLD.contract_id, OLD.snapshot_id, OLD.tentativa,
            OLD.request_sent_at, OLD.request_body, OLD.request_sha256, OLD.request_json)
        THEN
            RAISE EXCEPTION 'contract_submissions: campos do envio sao imutaveis';
        END IF;
        RETURN NEW;
    END
    $$
    """,
    *(
        f"""
        CREATE TRIGGER trg_{tabela}_imutavel BEFORE UPDATE OR DELETE ON contratos.{tabela}
        FOR EACH ROW EXECUTE FUNCTION contratos.proibir_alteracao()
        """
        for tabela in ("contract_events", "contract_snapshots")
    ),
    """
    CREATE TRIGGER trg_contract_submissions_resposta_unica
    BEFORE UPDATE OR DELETE ON contratos.contract_submissions
    FOR EACH ROW EXECUTE FUNCTION contratos.submissao_resposta_unica()
    """,
    *(
        f"""
        CREATE TRIGGER trg_{tabela}_sem_truncate BEFORE TRUNCATE ON contratos.{tabela}
        FOR EACH STATEMENT EXECUTE FUNCTION contratos.proibir_alteracao()
        """
        for tabela in ("contract_events", "contract_snapshots", "contract_submissions")
    ),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("pedido_sysfertil", sa.Text(), nullable=True),
        sa.Column("entrada", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sap_contract_number", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("origin IN ('WEB', 'API')", name=op.f("ck_contracts_origin")),
        sa.CheckConstraint(
            "pedido_sysfertil <> ''", name=op.f("ck_contracts_pedido_sysfertil_nao_vazio")
        ),
        sa.CheckConstraint(
            "sap_contract_number ~ '^[0-9]{10}$'",
            name=op.f("ck_contracts_sap_contract_number_vbeln"),
        ),
        sa.CheckConstraint(
            "status IN ('RASCUNHO', 'NA_FILA', 'ENVIANDO', 'CRIADO', 'ERRO_NEGOCIO', 'ERRO_TECNICO', 'INCERTO', 'CANCELADO')",
            name=op.f("ck_contracts_status"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_contracts_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_contracts_idempotency_key")),
        schema="contratos",
    )
    op.create_index(
        "uq_contracts_pedido_sysfertil_ativo",
        "contracts",
        ["pedido_sysfertil"],
        unique=True,
        schema="contratos",
        postgresql_where=sa.text(
            "pedido_sysfertil IS NOT NULL AND status NOT IN ('ERRO_NEGOCIO', 'CANCELADO')"
        ),
    )
    op.create_table(
        "sap_heartbeat",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("ultimo_csrf_ok", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_sap_heartbeat_linha_unica")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sap_heartbeat")),
        schema="contratos",
    )
    op.create_table(
        "contract_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("de", sa.Text(), nullable=False),
        sa.Column("para", sa.Text(), nullable=False),
        sa.Column("evento", sa.Text(), nullable=False),
        sa.Column("ator_kind", sa.Text(), nullable=False),
        sa.Column("ator_identifier", sa.Text(), nullable=False),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("sap_contract_number", sa.Text(), nullable=True),
        sa.Column("detalhe", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ator_identifier <> ''", name=op.f("ck_contract_events_ator_identifier")
        ),
        sa.CheckConstraint(
            "ator_kind IN ('user', 'admin', 'worker', 'system')",
            name=op.f("ck_contract_events_ator_kind"),
        ),
        sa.CheckConstraint(
            "de IN ('RASCUNHO', 'NA_FILA', 'ENVIANDO', 'CRIADO', 'ERRO_NEGOCIO', 'ERRO_TECNICO', 'INCERTO', 'CANCELADO')",
            name=op.f("ck_contract_events_de"),
        ),
        sa.CheckConstraint(
            "evento IN ('SUBMETER', 'CANCELAR', 'WORKER_PEGOU', 'SAP_201', 'SAP_4XX_NEGOCIO', 'SAP_4XX_TECNICO', 'FALHA_ANTES_POST', 'FALHA_ANTES_POST_ESGOTOU', 'TIMEOUT_APOS_POST', 'CONEXAO_CAIDA_APOS_POST', 'SAP_5XX_APOS_POST', 'LOCK_EXPIRADO_SEM_ENVIO', 'LOCK_EXPIRADO_COM_ENVIO', 'LIBERAR_REENVIO', 'RECONCILIAR_PARA_CRIADO', 'CONFERENCIA_DIVERGENTE', 'FALHA_APOS_RESPOSTA', 'FALHA_NAO_CLASSIFICADA_ANTES_ENVIO', 'FALHA_NAO_CLASSIFICADA_APOS_ENVIO')",
            name=op.f("ck_contract_events_evento"),
        ),
        sa.CheckConstraint(
            "para IN ('RASCUNHO', 'NA_FILA', 'ENVIANDO', 'CRIADO', 'ERRO_NEGOCIO', 'ERRO_TECNICO', 'INCERTO', 'CANCELADO')",
            name=op.f("ck_contract_events_para"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contratos.contracts.id"],
            name=op.f("fk_contract_events_contract_id_contracts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_events")),
        schema="contratos",
    )
    op.create_index(
        "ix_contract_events_contract_id",
        "contract_events",
        ["contract_id", "id"],
        unique=False,
        schema="contratos",
    )
    op.create_table(
        "contract_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("algoritmo_parcelas", sa.Text(), nullable=False),
        sa.Column("entrada_parcelas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "algoritmo_parcelas <> ''", name=op.f("ck_contract_snapshots_algoritmo_parcelas")
        ),
        sa.CheckConstraint("total > 0", name=op.f("ck_contract_snapshots_total")),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contratos.contracts.id"],
            name=op.f("fk_contract_snapshots_contract_id_contracts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_snapshots")),
        schema="contratos",
    )
    op.create_index(
        "ix_contract_snapshots_contract_id",
        "contract_snapshots",
        ["contract_id"],
        unique=False,
        schema="contratos",
    )
    op.create_table(
        "outbox_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("run_after", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lock_token", sa.UUID(), nullable=True),
        sa.Column("locked_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("concluido_em", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('CREATE')", name=op.f("ck_outbox_jobs_kind")),
        sa.CheckConstraint(
            "(lock_token IS NULL) = (locked_until IS NULL)", name=op.f("ck_outbox_jobs_lock_par")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_jobs_attempts")),
        sa.CheckConstraint(
            "concluido_em IS NULL OR lock_token IS NULL",
            name=op.f("ck_outbox_jobs_concluido_sem_lock"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contratos.contracts.id"],
            name=op.f("fk_outbox_jobs_contract_id_contracts"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["contratos.contract_snapshots.id"],
            name=op.f("fk_outbox_jobs_snapshot_id_contract_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_jobs")),
        sa.UniqueConstraint("seq", name=op.f("uq_outbox_jobs_seq")),
        schema="contratos",
    )
    op.create_index(
        "ix_outbox_jobs_pendentes",
        "outbox_jobs",
        ["run_after", "seq"],
        unique=False,
        schema="contratos",
        postgresql_where=sa.text("concluido_em IS NULL"),
    )
    op.create_table(
        "contract_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("tentativa", sa.Integer(), nullable=False),
        sa.Column("request_sent_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("request_body", sa.LargeBinary(), nullable=False),
        sa.Column("request_sha256", sa.Text(), nullable=False),
        sa.Column("request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.LargeBinary(), nullable=True),
        sa.Column("response_truncado", sa.Boolean(), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sap_messages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_class", sa.Text(), nullable=True),
        sa.Column("respondido", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "request_sha256 = encode(sha256(request_body), 'hex')",
            name=op.f("ck_contract_submissions_request_sha256"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_contract_submissions_duration_ms"),
        ),
        sa.CheckConstraint(
            "response_body IS NULL OR octet_length(response_body) <= 1048576",
            name=op.f("ck_contract_submissions_response_1mib"),
        ),
        sa.CheckConstraint("tentativa >= 1", name=op.f("ck_contract_submissions_tentativa")),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contratos.contracts.id"],
            name=op.f("fk_contract_submissions_contract_id_contracts"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["contratos.outbox_jobs.id"],
            name=op.f("fk_contract_submissions_job_id_outbox_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["contratos.contract_snapshots.id"],
            name=op.f("fk_contract_submissions_snapshot_id_contract_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_submissions")),
        schema="contratos",
    )
    op.create_index(
        "uq_contract_submissions_job_tentativa",
        "contract_submissions",
        ["job_id", "tentativa"],
        unique=True,
        schema="contratos",
    )
    # ### end Alembic commands ###
    for sql in _IMUTABILIDADE:
        op.execute(sql)
    op.execute("INSERT INTO contratos.sap_heartbeat (id, ultimo_csrf_ok) VALUES (1, NULL)")


def downgrade() -> None:
    # DROP TABLE nao dispara trigger; as funcoes saem depois das tabelas.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_contract_submissions_job_tentativa",
        table_name="contract_submissions",
        schema="contratos",
    )
    op.drop_table("contract_submissions", schema="contratos")
    op.drop_index(
        "ix_outbox_jobs_pendentes",
        table_name="outbox_jobs",
        schema="contratos",
        postgresql_where=sa.text("concluido_em IS NULL"),
    )
    op.drop_table("outbox_jobs", schema="contratos")
    op.drop_index(
        "ix_contract_snapshots_contract_id", table_name="contract_snapshots", schema="contratos"
    )
    op.drop_table("contract_snapshots", schema="contratos")
    op.drop_index(
        "ix_contract_events_contract_id", table_name="contract_events", schema="contratos"
    )
    op.drop_table("contract_events", schema="contratos")
    op.drop_table("sap_heartbeat", schema="contratos")
    op.drop_index(
        "uq_contracts_pedido_sysfertil_ativo",
        table_name="contracts",
        schema="contratos",
        postgresql_where=sa.text(
            "pedido_sysfertil IS NOT NULL AND status NOT IN ('ERRO_NEGOCIO', 'CANCELADO')"
        ),
    )
    op.drop_table("contracts", schema="contratos")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION contratos.proibir_alteracao()")
    op.execute("DROP FUNCTION contratos.submissao_resposta_unica()")
